services:
  - name: server
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start

  - name: client
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s build